// fila/feitos.js — itens entregues. Histórico: não se edita à mão;
// `node tools/fila.mjs concluir <id> "<meta>"` acrescenta o item que a PR entrega.
const ITENS = [
  {"id":"E5","camada":0,"e":"feito","quem":"feito","nome":"Branch redesign-dashboard: apagar","meta":"entregue 27/09 · branch redesign-dashboard apagada (já estava mergeada)","desc":"A branch local `redesign-dashboard` continua existindo. Apurado em 26/09: ela não tem nenhum commit que não esteja no master (já foi mergeada). Menos ruído na lista de branches.","exige":[],"destrava":[]},
  {"id":"E4","camada":0,"e":"feito","quem":"feito","nome":"Docs desatualizados: roadmap, estrutura do README, seção do Inc 3","meta":"entregue 28/09 · roadmap com 1, 1.5 e 3 implementados, seção do Inc 3 no CLAUDE.md e árvore do README batendo com o repo","desc":"O roadmap do `CLAUDE.md` ainda mostra 1.5 como fast-follow e 3 como futuro, apesar de entregues. A estrutura no `README.md` cita arquivos que mudaram, e o `CLAUDE.md` não tem seção do Inc 3. Quem abre o projeto (inclusive os agentes da fila) lê o estado real.","exige":[],"destrava":[]},
  {"id":"F3","camada":0,"e":"feito","quem":"feito","nome":"Entrada malformada nas rotas de grupo vira 500","meta":"entregue 28/09 · rotas /api/grupos respondem 400 para id não-uuid e ids não-lista (ehUuid em worker/validar.js)","desc":"Id que não é uuid ou `ids` que não é lista nas rotas `/api/grupos` estoura no cast do SQL e responde 500. Erro de entrada responde 400 com mensagem, não 500.","exige":[],"destrava":[]},
  {"id":"F2","camada":0,"e":"feito","quem":"feito","nome":"Aplicar depois de preview velho pode deixar grupo sem representante","meta":"entregue 29/09 · aplicar com prévia velha responde 409 sem gravar; agrupar em grupo sem representante responde 400","desc":"Se o grupo foi dissolvido entre o preview e o aplicar do import, a linha do extrato pode entrar num grupo sem representante. `decidirAgrupar` também não confere que o grupo existente tem representante. Nenhum grupo fica sem quem conta no Resumo.","exige":[],"destrava":[]},
  {"id":"B2","camada":0,"e":"feito","quem":"feito","nome":"Painel de regras aprendidas no app","meta":"entregue 29/09 · painel de regras aprendidas na aba Ajustes: lista mascarada, busca, editar (mantém n) e remover","desc":"As associações aprendidas (contraparte → categoria) não são visíveis nem editáveis no app. Para corrigir uma regra errada é preciso fazer uma correção nova ou rodar os tools Python. Ver, editar e remover as regras que o classificador usa, na aba Ajustes, sem sair do app.","exige":[],"destrava":[]},
  {"id":"C3","camada":0,"e":"feito","quem":"feito","nome":"Re-aplicar fatura marca o pagamento no extrato de novo","meta":"entregue 29/09 · reaplicar fatura não remarca: pagamento já fora do resumo na janela bloqueia a marcação","desc":"Aplicar a mesma fatura duas vezes não duplica as compras (o `linha_hash` deduplica), mas a marcação do pagamento no extrato não é idempotente. Poder re-aplicar uma fatura sem medo de bagunçar o extrato.","exige":[],"destrava":[]},
  {"id":"B5","camada":0,"e":"feito","quem":"feito","nome":"Texto manual: \"R$ \" vaza para a descrição e valor só-milhar não é reconhecido","meta":"entregue 29/09 · texto manual: R$ separado não vaza para a descrição e 1.500 é milhar; 1.50 recusado","desc":"No lançamento por texto no Telegram, \"R$ \" antes do valor vai parar na descrição, e um valor escrito só com milhar sem centavos não é reconhecido. Lançar por texto do jeito que se digita naturalmente, sem ter que corrigir depois no app.","exige":[],"destrava":[]},
  {"id":"E6","camada":0,"e":"feito","quem":"feito","nome":"Logs persistidos do Worker","meta":"entregue 29/09 · wrangler.toml com [observability] enabled = true (Workers Logs nativo)","desc":"`[observability]` está desligado no `wrangler.toml`: um erro do webhook só aparece se alguém estiver com `wrangler tail` aberto na hora. Foi assim que o bot ficou mudo sem ninguém saber (B1). Poder olhar depois o que deu errado no Worker.","exige":[],"destrava":[]},
  {"id":"E1","camada":0,"e":"feito","quem":"feito","nome":"Teste do app sai do public/ (hoje vai no deploy)","meta":"entregue 01/10 · app.test.mjs sai de public/ para tests/ (só rename + imports), npm test aponta para lá","desc":"`public/app.test.mjs` está dentro da pasta servida como asset, então vai no deploy e fica acessível no app no ar. O deploy carrega só o que o app usa.","exige":[],"destrava":[]},
  {"id":"C2","camada":0,"e":"feito","quem":"feito","nome":"Aba Importar: casar manualmente um ambíguo com um candidato","meta":"entregue 01/10 · ambíguo do extrato lista os candidatos e casa com o escolhido na aba Importar","desc":"Quando a linha do extrato tem mais de um candidato, a única ação na aba Importar é \"tratar como novo\". Se um dos candidatos é o lançamento certo, vira duplicata e tem que ser agrupada à mão depois. Resolver o ambíguo na hora do import, escolhendo o candidato certo, e a linha do extrato já entra no grupo dele.","exige":[],"destrava":[]},
  {"id":"F4","camada":0,"e":"feito","quem":"feito","nome":"Membros órfãos aparecem editáveis na tabela","meta":"entregue 02/10 · membro órfão vira só leitura (texto, ★ e ⤴) e sai do selecionar todos","desc":"Membro de grupo cujo representante está fora do período aparece com os controles de edição completos, e o \"fora do resumo\" nele não afeta o Resumo. Membro nunca parece editável quando a edição não tem efeito.","exige":[],"destrava":[]},
  {"id":"E2","camada":0,"e":"feito","quem":"feito","nome":"Trava contra regressão do escape no app (esc exportada e testada)","meta":"entregue 02/10 · esc() exportada de public/app.js com teste de escape em tests/app.test.mjs","desc":"O app monta partes da tela com `innerHTML` usando descrição e nomes vindos do banco (comprovante lido por modelo, extrato). Hoje está tudo escapado: `esc()` existe em `public/app.js` desde 30/08/2026 e a apuração do PM de 02/10 conferiu os 35 pontos de `innerHTML`. Mas `esc()` mora dentro do bloco do navegador, sem teste: se ela quebrar ou um `innerHTML` novo esquecer de usá-la, nada avisa. Uma regressão no escape quebra o `npm test` em vez de chegar à tela.","exige":[],"destrava":[]},
  {"id":"D6","camada":0,"e":"feito","quem":"feito","nome":"Sunburst pessoa → categoria e novo layout do Resumo","meta":"entregue 02/10 · sunburst pessoa → categoria (porPessoaCategoria no /api/resumo) no lugar da rosca, e Resumo em 4 blocos","desc":"O gasto por pessoa aparece só numa rosca, sem dizer em que categoria cada pessoa gasta; e o Resumo tem quatro linhas de cards em que o sunburst de categoria divide a primeira linha com \"Gasto no mês\". Ver de uma vez em que categoria cada pessoa gasta, sem abrir Lançamentos.","exige":[],"destrava":[]},
  {"id":"F1","camada":0,"e":"feito","quem":"feito","nome":"Grupo com foto + manual de mesmo valor deixa o extrato ambíguo","meta":"entregue 02/10 · grupo conta como um candidato só no import; caso misto mostra 'grupo: <descrição> (N lançamentos)'","desc":"Um grupo com foto e lançamento manual da mesma despesa (mesmo valor) aparece como dois candidatos para a linha do extrato no import, que fica ambígua — mesmo os dois sendo a mesma despesa. A linha do extrato casa direto no grupo.","exige":[],"destrava":[]},
  {"id":"C1","camada":0,"e":"feito","quem":"feito","nome":"Importar extrato do C6 Bank","meta":"entregue 02/10 · extrato do C6 Bank na aba Importar (PDF com senha), PIX TRANSF do Caio conta como receita no Itaú e o repasse C6→Itaú sai do resumo nas duas pontas","desc":"O parser de extrato só entende o Itaú. A conta PJ fica no C6 Bank e recebe da Wise só o necessário para pagar as contas da empresa (impostos, contador, plano de saúde); o resto da conversão vai direto para o Itaú. Nada do C6 entra hoje. As despesas da empresa pagas pelo C6, e o dinheiro da Wise que as paga, passam a existir no sistema. A receita fica contada uma vez só: na chegada da Wise em reais, em qualquer conta do Caio.","exige":[],"destrava":["A1"]},
  {"id":"C8","camada":0,"e":"feito","quem":"feito","nome":"Fatura: parcela com o ano errado vai parar no futuro","meta":"entregue 08/10 · parcela da fatura no mês da fatura, preview acha a chave antiga, migração 0010 volta um ano as 81 linhas","desc":"A fatura do Itaú traz só dia e mês da compra, e o parser completa com o ano da fatura. Uma parcela de compra feita no fim do ano anterior (ex.: compra de outubro, parcela 12/12 na fatura de setembro do ano seguinte) ganha o ano da fatura e cai num mês futuro. O mesmo vale para compra de dezembro numa fatura de janeiro. Em 2026-10-08 havia 78 linhas de fatura com data futura, inflando outubro a dezembro de 2026, e mais 3 parcelas de compras de 2025 datadas em junho, agosto e setembro de 2026 — 81 no total, todas nas faturas de 2026 importadas em 2026-09-08. O mês de cada gasto do cartão é o mês em que ele pesou na fatura, e nenhum mês futuro mostra gasto que não aconteceu.","exige":[],"destrava":[]},
  {"id":"G1","camada":0,"e":"feito","quem":"feito","nome":"Saldo do mês confiável: salário por competência, investimento fora do resumo","meta":"entregue 10/10 · salário por competência (FIFO das conversões Wise/Nomad), card Saldo do mês + 12 meses, resgate/aplicação e chegada da Wise fora do resumo, migrações 0011/0012","desc":"O \"saldo do mês\" do Resumo não diz se a família fecha o mês no azul. Dois motivos, vistos no banco em 2026-10-09: 1. Aplicação e resgate de investimento contam como despesa e receita (em março de 2026, uma aplicação e o resgate correspondente, de centenas de milhares, entraram nos dois lados; resgates aparecem como receita em fevereiro, março e abril). 2. A receita chega em blocos: a Wise converte dólar em reais quando o Caio pede, e um mês mostra o salário de três meses enquanto o seguinte mostra quase nada. O salário real é fixo em dólar (hoje USD 8.000 por mês) e varia só pelo câmbio da conversão. Um número por mês, comparável entre meses: receita do mês (salário convertido ao câmbio real) menos as despesas que contam. É o dado que o Diagnóstico (G3) e o Projeto Casa (G4) leem.","exige":[],"destrava":["G3","G4","C7"]},
  {"id":"G2","camada":0,"e":"feito","quem":"feito","nome":"Fechamento do mês: o que falta importar","meta":"entregue 10/10 · tabela importacoes gravada no aplicar, /api/fechamento e bloco de fechamento do mês no Resumo","desc":"Para fechar a visão de um mês, o Caio precisa ter importado o extrato do Itaú, o do C6 e a fatura, e tratado o que ficou sem categoria. Hoje nada diz o que falta: em 2026-10-09, setembro não tinha fatura importada e outubro não tinha extrato do Itaú, e só uma consulta no banco mostrava isso. Abrir o app e saber, por mês, o que ainda falta enviar para o saldo do mês ser confiável.","exige":[],"destrava":[]}
];
