// fila/feitos.js — itens entregues. Histórico: não se edita à mão;
// `node tools/fila.mjs concluir <id> "<meta>"` acrescenta o item que a PR entrega.
const ITENS = [
  {"id":"E5","camada":0,"e":"feito","quem":"feito","nome":"Branch redesign-dashboard: apagar","meta":"entregue 27/09 · branch redesign-dashboard apagada (já estava mergeada)","desc":"A branch local `redesign-dashboard` continua existindo. Apurado em 26/09: ela não tem nenhum commit que não esteja no master (já foi mergeada). Menos ruído na lista de branches.","exige":[],"destrava":[]},
  {"id":"E4","camada":0,"e":"feito","quem":"feito","nome":"Docs desatualizados: roadmap, estrutura do README, seção do Inc 3","meta":"entregue 28/09 · roadmap com 1, 1.5 e 3 implementados, seção do Inc 3 no CLAUDE.md e árvore do README batendo com o repo","desc":"O roadmap do `CLAUDE.md` ainda mostra 1.5 como fast-follow e 3 como futuro, apesar de entregues. A estrutura no `README.md` cita arquivos que mudaram, e o `CLAUDE.md` não tem seção do Inc 3. Quem abre o projeto (inclusive os agentes da fila) lê o estado real.","exige":[],"destrava":[]},
  {"id":"F3","camada":0,"e":"feito","quem":"feito","nome":"Entrada malformada nas rotas de grupo vira 500","meta":"entregue 28/09 · rotas /api/grupos respondem 400 para id não-uuid e ids não-lista (ehUuid em worker/validar.js)","desc":"Id que não é uuid ou `ids` que não é lista nas rotas `/api/grupos` estoura no cast do SQL e responde 500. Erro de entrada responde 400 com mensagem, não 500.","exige":[],"destrava":[]},
  {"id":"F2","camada":0,"e":"feito","quem":"feito","nome":"Aplicar depois de preview velho pode deixar grupo sem representante","meta":"entregue 29/09 · aplicar com prévia velha responde 409 sem gravar; agrupar em grupo sem representante responde 400","desc":"Se o grupo foi dissolvido entre o preview e o aplicar do import, a linha do extrato pode entrar num grupo sem representante. `decidirAgrupar` também não confere que o grupo existente tem representante. Nenhum grupo fica sem quem conta no Resumo.","exige":[],"destrava":[]},
  {"id":"B2","camada":0,"e":"feito","quem":"feito","nome":"Painel de regras aprendidas no app","meta":"entregue 29/09 · painel de regras aprendidas na aba Ajustes: lista mascarada, busca, editar (mantém n) e remover","desc":"As associações aprendidas (contraparte → categoria) não são visíveis nem editáveis no app. Para corrigir uma regra errada é preciso fazer uma correção nova ou rodar os tools Python. Ver, editar e remover as regras que o classificador usa, na aba Ajustes, sem sair do app.","exige":[],"destrava":[]},
  {"id":"C3","camada":0,"e":"feito","quem":"feito","nome":"Re-aplicar fatura marca o pagamento no extrato de novo","meta":"entregue 29/09 · reaplicar fatura não remarca: pagamento já fora do resumo na janela bloqueia a marcação","desc":"Aplicar a mesma fatura duas vezes não duplica as compras (o `linha_hash` deduplica), mas a marcação do pagamento no extrato não é idempotente. Poder re-aplicar uma fatura sem medo de bagunçar o extrato.","exige":[],"destrava":[]},
  {"id":"B5","camada":0,"e":"feito","quem":"feito","nome":"Texto manual: \"R$ \" vaza para a descrição e valor só-milhar não é reconhecido","meta":"entregue 29/09 · texto manual: R$ separado não vaza para a descrição e 1.500 é milhar; 1.50 recusado","desc":"No lançamento por texto no Telegram, \"R$ \" antes do valor vai parar na descrição, e um valor escrito só com milhar sem centavos não é reconhecido. Lançar por texto do jeito que se digita naturalmente, sem ter que corrigir depois no app.","exige":[],"destrava":[]},
  {"id":"E6","camada":0,"e":"feito","quem":"feito","nome":"Logs persistidos do Worker","meta":"entregue 29/09 · wrangler.toml com [observability] enabled = true (Workers Logs nativo)","desc":"`[observability]` está desligado no `wrangler.toml`: um erro do webhook só aparece se alguém estiver com `wrangler tail` aberto na hora. Foi assim que o bot ficou mudo sem ninguém saber (B1). Poder olhar depois o que deu errado no Worker.","exige":[],"destrava":[]},
  {"id":"E1","camada":0,"e":"feito","quem":"feito","nome":"Teste do app sai do public/ (hoje vai no deploy)","meta":"entregue 01/10 · app.test.mjs sai de public/ para tests/ (só rename + imports), npm test aponta para lá","desc":"`public/app.test.mjs` está dentro da pasta servida como asset, então vai no deploy e fica acessível no app no ar. O deploy carrega só o que o app usa.","exige":[],"destrava":[]},
  {"id":"C2","camada":0,"e":"feito","quem":"feito","nome":"Aba Importar: casar manualmente um ambíguo com um candidato","meta":"entregue 01/10 · ambíguo do extrato lista os candidatos e casa com o escolhido na aba Importar","desc":"Quando a linha do extrato tem mais de um candidato, a única ação na aba Importar é \"tratar como novo\". Se um dos candidatos é o lançamento certo, vira duplicata e tem que ser agrupada à mão depois. Resolver o ambíguo na hora do import, escolhendo o candidato certo, e a linha do extrato já entra no grupo dele.","exige":[],"destrava":[]},
  {"id":"F4","camada":0,"e":"feito","quem":"feito","nome":"Membros órfãos aparecem editáveis na tabela","meta":"entregue 02/10 · membro órfão vira só leitura (texto, ★ e ⤴) e sai do selecionar todos","desc":"Membro de grupo cujo representante está fora do período aparece com os controles de edição completos, e o \"fora do resumo\" nele não afeta o Resumo. Membro nunca parece editável quando a edição não tem efeito.","exige":[],"destrava":[]},
  {"id":"E2","camada":0,"e":"feito","quem":"feito","nome":"Trava contra regressão do escape no app (esc exportada e testada)","meta":"entregue 02/10 · esc() exportada de public/app.js com teste de escape em tests/app.test.mjs","desc":"O app monta partes da tela com `innerHTML` usando descrição e nomes vindos do banco (comprovante lido por modelo, extrato). Hoje está tudo escapado: `esc()` existe em `public/app.js` desde 30/08/2026 e a apuração do PM de 02/10 conferiu os 35 pontos de `innerHTML`. Mas `esc()` mora dentro do bloco do navegador, sem teste: se ela quebrar ou um `innerHTML` novo esquecer de usá-la, nada avisa. Uma regressão no escape quebra o `npm test` em vez de chegar à tela.","exige":[],"destrava":[]}
];
